config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"

resources :products
resources :upvotes, only: [:create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_attachment :photo
  belongs_to :user
  has_many :upvotes

  validates :user, presence: true
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
   validates :category, inclusion: { in: %w(tech education design),
    message: "%{value} is not a valid category" }
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user, uniqueness: { scope: :product }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attachment :avatar
  has_many :products
  has_many :upvotes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def voted_for?(product)
    product.upvotes.where(user: self).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user! #liste blanche



   before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    #devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 skip_before_action :authenticate_user!

  def home
    @today = Date.today
  end

  def team
    @members = ["kara", "imane", "adam"]
  end

  def join_us
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category]
      @products = Product.where(category: params[:category])
    else
    @products = Product.all
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.user == current_user
        @product.update(product_params)
        redirect_to products_path
    else
      flash[:alert] = "Action impossible, ce produit n'est pas le votre."
      render :edit
    end
  end

  def destroy
    if @product.user == current_user
    @product.destroy
    redirect_to products_path
    else

    end

  end

#Autorise uniquement  name et url
  private

  def product_params
    params.require(:product).permit(:name, :url, :tagline, :category, :photo)
  end

  def find_product
  @product = Product.find(params[:id])
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @product.upvotes.create! user: current_user
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end

  end

  def destroy

    upvote = Upvote.find(params[:id])
    @product = upvote.product
    upvote.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
   <%= render "shared/navbar" %>
   <%= render "shared/flashes" %>


    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "wagon.jpg"%>');">
  <div class="banner-content">
    <h1>Chooze Hunt</h1>
    <p>Find best tech products</p>
    <%= link_to "All products", products_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= link_to "Design", products_path(category: "design"), class: "card-category design"%>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= link_to "Tech", products_path(category: "tech"), class: "card-category tech"%>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= link_to "Education", products_path(category: "education"), class: "card-category education"%>
    </div>
  </div>
</div>

app/views/pages/team.html.erb
<div class="container text-center">
  <h1>Meet the team</h1>

  <%= cl_image_tag "uecxqq8vye66uccgrxht", height: 100, width: 400, crop: :fill %>
  <ul>
    <% @members.each do |member| %>
    <li>Member : <%= member %></li>
    <% end %>

  </ul>
</div>

app/views/products/_form.html.erb
 <%= simple_form_for @product do |f| %>
         <%=f.input :name, placeholder: "Kudoz", label: "Which product?"%>
         <%=f.input :url, placeholder: "http://getkudoz.com", label: "Which url?"%>
         <%=f.input :tagline, placeholder: "Tinder for job search", label: "Which tagline?"%>
         <%=f.input :category, collection: ["tech", "education", "design"], prompt: "Which category?"%>
         <%= f.input :photo, as: :attachinary %>
         <%=f.button :submit, "Ajouter", class: "btn btn-primary" %>

    <% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

    <h1>Editer le produit</h1>

    <%= render "form" %>



    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center">All products</h1>

    <% @products.each do |product| %>


  <div class="product">

  <div class="upvote-container" id="product-<%= product.id %>">
    <%= render "upvotes/show", product: product %>
  </div>
  <% if product.photo %>
    <%= cl_image_tag(product.photo.path, height: 117, width: 175, crop: :fill, class: "product-image")%>
  <% else %>
  <img src="http://unsplash.it/300/200?random" alt="kudoz" class="product-image">
  <% end %>

  <div class='product-body'>
    <h3><%= product.name %></h3>
    <p><%= product.tagline %></p>
  </div>
  <ul class="list-inline product-controls hidden-sm hidden-xs">
    <li>
    <%= link_to product_path(product) do %>
    <i class="fa fa-eye"></i>
    <% end %>
    </li>
    <li>
    <%= link_to edit_product_path(product) do %>
    <i class="fa fa-pencil"></i>
    <% end %>
    </li>

    <li>
    <%= link_to product_path(product), method: :delete do %>
    <i class="fa fa-trash"></i>
    <% end %>
    </li>

  </ul>
</div>
  <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

    <h1>Ajouter un produit</h1>

    <%= simple_form_for @product do |f| %>
         <%=f.input :name, placeholder: "Kudoz", label: "Which product?"%>
         <%=f.input :url, placeholder: "http://getkudoz.com", label: "Which url?"%>
         <%=f.button :submit, "Ajouter", class: "btn btn-primary" %>

    <% end %>

    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @product.photo? ? cloudinary_url(@product.photo.path, width: 1280, height: 700, crop: :fill) : image_path("wagon.jpg"); %>');">
  <div class="banner-content">
    <h1><%= @product.name %></h1>
    <p><%= @product.tagline %>
    <span class="label label-default">
      <%= @product.category %>
    </span>
    </p>
    <% if @product.user %>
    <p>
      Posté par <%= @product.user.email %>
    </p>
    <% end %>
    <%= link_to cloudinary_url(@product.photo.path, :resource_type => :raw) do  %>
    <i class="fa fa-eye"></i>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
 <% if notice %>
     <div class="alert alert-info alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <%= notice %>
     </div>
   <% end %>
   <% if alert %>
     <div class="alert alert-warning alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <%= alert %>
     </div>
   <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "lewagon.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  <% if user_signed_in? %>
    <!-- Text link -->
    <%= link_to "All products", products_path, class: "navbar-wagon-item navbar-wagon-link"%>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag current_user.avatar.path, width:80, height:80, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :'data-toggle' => 'dropdown' %>
        <% else %>
          <img src="http://placehold.it/30x30" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
          <%= link_to "Profile", edit_user_registration_path %>
          </li>
          <li><a href="#">Dashboard</a></li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to "Add product", new_product_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

  <% else %>

  <%= link_to "Sign in ", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

  <% end %>

  </div>
  </div>

  <!-- Dropdown appearing on mobile only -->

  <div class="navbar-wagon-item hidden-md hidden-lg">
     <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li>
          <%= link_to "All products", products_path %>
        </li>

         <li>
          <%= link_to "Profile", edit_user_registration_path %>
          </li>

           <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
         </li>
      </ul>

      <% else %>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

           <li>
          <%= link_to "All products", products_path %>
        </li>

          <li>
              <%= link_to "Sign in ", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
           <li>
              <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
           </li>
        </ul>

  <% end %>
</div>
</div>
</div>

app/views/upvotes/_show.html.erb
<% if user_signed_in? %>

    <% if current_user.voted_for?(product) %>
     <%= link_to upvote_path(current_user.upvotes.where(product: product).first),remote: true, method: :delete,  class: "product-upvote product-upvoted" do %>
      <div class="product-arrow"></div>
        <div class='product-count'>
          <%= product.upvotes.size %>
        </div>
         <%end%>
    <%else%>
      <%= link_to upvotes_path(product_id: product.id), remote: true, method: :post,  class: "product-upvote" do %>
      <div class="product-arrow"></div>
        <div class='product-count'>
          <%= product.upvotes.size %>
        </div>
      <%end%>
    <%end%>

  <%else%>
   <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>
      <%= product.upvotes.size %>
    </div>
  </div>
  <%end%>

app/views/upvotes/create.js.erb
$("#product-<%= @product.id%>").html("<%= j render "upvotes/show", product: @product %>");

app/views/upvotes/destroy.js.erb
$("#product-<%= @product.id%>").html("<%= j render "upvotes/show", product: @product %>");